name: m2hub
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
  - nvidia
  - dglteam 
dependencies:
  - python=3.9.*
  - pytorch-cuda=11.6
  - ase=3.21.1
  - black==22.3.0
  - matplotlib
  - numba
  - pip
  - pre-commit=2.10.*
  - pyg=2.2.0
  - pymatgen
  - python-lmdb
  - pytorch=1.13.1
  - torchvision==0.14.1 
  - torchaudio==0.13.1
  - pyyaml
  - tensorboard
  - tqdm
  - pytest
  - submitit
  - syrupy=3.0.6
  - wandb==0.14.0
  - rdkit
  - dgl
  - jarvis-tools
  - pydantic
  - scikit-learn
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-spline-conv
  - pip: 
    - rdkit
    - scipy
    - torch-geometric
    - joblib
    - fuzzywuzzy
    - matbench
    - e3nn



