includes:
- configs/jarvis/edos_pdos/edos/random/base.yml

model:
 name: alignn
 cutoff: 8.0
 max_neighbors: 12
 alignn_layers: 3
 gcn_layers: 3
 num_gaussians: 80
 triplet_input_features: 40
 embedding_features: 64
 atom_embedding_size: 128
 link: "identity"
 regress_forces: False
 use_pbc: True
 otf_graph: True
 output_dim: 300

optim:
 batch_size: 32
 eval_batch_size: 32
 num_workers: 4
 lr_initial: 0.001
 optimizer: AdamW
 lr_gamma: 0.1
 lr_milestones:
  - 5000000000
 warmup_steps: -1
 warmup_factor: 1.0
 max_epochs: 500
 weight_decay: 0.00001
 eval_every: 500
