includes:
  - configs/jarvis/edos_pdos/edos/random/base.yml

model:
  name: cgcnn
  atom_embedding_size: 128
  fc_feat_size: 256
  num_fc_layers: 4
  num_graph_conv_layers: 5
  cutoff: 6.0
  num_gaussians: 100
  output_dim: 300
  regress_forces: False
  use_pbc: True
  otf_graph: False

optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers:  4
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: 
    - 5000000000
  warmup_steps: -1
  warmup_factor: 1.0
  max_epochs: 500
  eval_every: 200
