includes:
- config/jarvis/qmof/bandgap/random/base.yml

model:
 name: leftnet
 cutoff: 6.0
 hidden_channels: 128
 num_layers: 4
 num_radial: 32
 regress_forces: False
 use_pbc: True
 otf_graph: False

optim:
 batch_size: 8
 eval_batch_size: 8
 num_workers: 4
 lr_initial: 0.0005
 lr_gamma: 0.1
 lr_milestones:
  - 5000000000
 warmup_steps: -1
 warmup_factor: 1.0
 max_epochs: 10
 eval_every: 500
