includes:
  - configs/jarvis/edos_pdos/edos/random/base.yml

model:
  name: schnet
  hidden_channels: 128
  num_filters: 5
  num_interactions: 6
  num_gaussians: 50
  cutoff: 6.0
  output_dim: 300
  use_pbc: True
  regress_forces: False

optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers:  4
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: 
    - 5000000000
  warmup_steps: -1
  warmup_factor: 1.0
  max_epochs: 500
  eval_every: 200
